<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>About CISVisual </h1>
	<p>CISVisual was originally developed as a site about anime. During the summer of 2006, I started piecing together bits of code intended to be something akin to Anime News Network, only built exclusively for the members of a local anime club to use. Of course, the anime club itself never got off the ground, and the code sat unused until the wintertime. Seeing no reason why the work should go to waste, the site was rebuilt with the goal of becoming the largest source of information for anime, manga and visual novels combined.</p>
	<p>In July of 2007, I realized that the anime and manga websites had been done to death, and decided to focus my attention instead on a medium that had recently begun grabbing my attention in a big way. The site was quickly overhauled to prep it for a live beta, which was subsequently launched for the visual novel community in early August. The beta ran for approximately two months before I decided it was time to buckle down and get a final working version out the door. The result of that decision is what you see here today.</p>
	<p>&nbsp;</p>
	<p>As the creator of CISVisual, it has been my goal to help introduce people to the world of visual novels by giving them a site with which they can enter this realm and explore to their heart's content. At the same time, I also want to provide useful functionality to people who already have a knowledge of visual novels, and want to branch out and find new titles to enjoy. The English-speaking anime and manga communities have many sites dedicated to serving them information, why should English-speaking fans of visual novels be left out? I am committed to creating the best possible site for the advancement of visual novels in the public eye, by increasing the amount of information readily available for people interested in this amazing medium. I only hope my efforts to be successful at these goals will be useful to others.   --3dB</p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
