<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Frequently Asked Questions</h1>

	<p>&nbsp;</p>
	<h3>What is a Visual Novel? </h3>
	<p>Wikipedia defines a visual novel as &quot;...an interactive fiction game featuring mostly static graphics, usually with anime-style art.&quot; However, they can be much more than that. Present-day visual novels vary in type but most often allow the player to choose their own path through a story comprised of many different intertwining arcs. Most visual novels rely on still images imposed over a rich background with accompanying text to advance the story, but many also have specially composed soundtracks and even a full voice dialogue to compliment these aspects. Visual novels have also begun including full video sequences as another way to enhance the player's experience.</p>
	<p>&nbsp;</p>
	<h3>What is the Appeal of a Visual Novel?</h3>
	<p>Visual novels appeal to many people for different reasons. They offer a unique experience similar to a cross between watching an anime and reading a book that also manages to include a level of interactivity. There are a lot of very serious visual novels that are centered around heavy character development and plot advancement, but there are also visual novels made just for fun that explore the lighter side of the medium. Recently, there has been a growing trend in the anime industry to turn certain visual novels into animated works that has given the format much attention.</p>
	<p>&nbsp;</p>
	<a name="translation"></a><h3>What Does it Mean When a Visual Novel is Referred to as "Localized" or "Licensed"?</h3>
	<p>These terms are used in reference to a title's availability translated into the English language. When a visual novel is described on the site as "localized", it means that a fan group has independently translated a title and released a publicly available patch. When a visual novel has been licensed, this means that a private company has purchased the right to the VN and has produced a translated version that is available for purchase.
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
