<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>
<?= $this->render('menu.phtml') ?>

<div id="Content">
	<h1>A Special Note for Visitors from No Name Losers</h1>
	<p>No doubt you have reached my site after reading the curious writings of a member from the group <i>No Name Losers</i> who decided to teach me a lesson and "out" the private message I sent him. I'm actually quite glad he did it, as the only reason why I sent it to him as a private message was to spare the rest of the forum my explicit words. Unlike him, I prefer to keep my heated arguments between my opponent and I. I make the conscious decision not to turn entire threads into hate-filled flame wars, which is surely what such a post would have done. Now my words are being reproduced in a venue where they actually belong, and if you read the rest of the NNL main page you'll see exactly what I mean.</p>
	<p>For you, the reader, I recreate here the one and only statement you'll ever see on this site about the whole ridiculous situation:</p>
	<p>&nbsp;</p>
	<p>"When I checked my site statistics today, I noticed an unusual amount of hits. At first I thought that maybe Google had re-crawled my site and I'd been moved up a notch, but no such luck. Instead it seems that I've been lit up by a member of the <a href="http://www.nnl1.com">No Name Losers</a>, the group responsible for the English translation of <i>Wind -a breath of heart-</i> as well as several other works. There's really not much to say about the whole thing. I will stand by every word I said, no matter how tactless they may be. To provide a little context and help you understand why I'd make such a statement, I offer to you the <a href="http://forums.visualnews.net/showthread.php?t=17130">thread on the Gemot</a> that fueled my words of anger. Armed with these two pieces of information, make any judgment of me you like from this situation."</p>
	<p>&nbsp;</p>
	<p>When you're finished digesting the latest round of drama from NNL, please feel free to have a look around the site! Development is continually ongoing, and all questions and comments are welcomed.</p>
	<p>&nbsp;</p>
	<p class="indent"><strong style="font-size: large">--3dB</strong></h3>
</div>

<?= $this->render('footer.phtml') ?>
