<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Rating Submitted</h1>
	<p>Success! Your overall rating of <?= $this->rating ?> for "<?= $this->titleName ?>" has been entered into the database.</p>
	<p>&nbsp;</p>
	<p><a href="<?= $this->baseUrl . '/title/' . $this->titleID ?>">&lt;&lt; Return to <?= $this->titleName ?></a></p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
