<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Error!</h1>
	<p>Uh oh, CISVisual has encountered an error when trying to process your visual novel submission. The details of this error have been logged. Please contact a staff member about this error so that it can be resolved.</p>
	<p>&nbsp;</p>
	<p><a href="<?= $this->baseUrl ?>/forum/index.php?board=13.0" title="Bug Report Forum">CISVisual Bug Report Forum >></a></p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
