<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Add a Visual Novel</h1>
	<p>Success! Your title has been entered into the database and will be reviewed by a staff member before it is officially listed on the site. Under normal circumstances, title are typically reviewed in less than 48 hours from the time of submission, so check back to see if it has been approved!</p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
