<div id="Footer">
<p> CISVisual <?= $this->version ?> -- Created by <a href="mailto:admin@cisvisual.net">3dB</a> -- Style adapted from <a href="http://www.bluerobot.com/web/layouts/" title="Blue Robot Layout Reservoir">BlueRobot</a>
<? /* <br />Page created in <? global $stopwatch; echo microtime(true) - $stopwatch ?> seconds | <a href="http://framework.zend.com/"><img border="0" style="vertical-align: middle" src="<?= $this->baseUrl . '/images/PoweredByZF.png' ?>" alt="Powered by Zend Framework" /></a></p> */ ?>
</div>

</body>
</html>
