<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>
<div id="Content">
	<h1>CISVisual -- Please Log In</h1>
	<p>The page you are trying to view requires you to be logged in. Please do so by using the login form located at the top of the page. If you do not have account, you can register for one by clicking the link to the right of the login box.</p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
