<div id="Menu">
  <p style="display: inline"><a href="<?= $this->baseUrl ?>/" title="CISVisual Main">CISVisual Main</a><br />
    <a href="<?= $this->baseUrl ?>/list" title="CISystem Visual Novel Index">Visual Novel Index</a><br />
    &nbsp;-&nbsp;<a href="<?= $this->baseUrl ?>/title/add" title="Add a Visual Novel to the Index">Add a Title</a><br />
    <!-- <a href="#" title="CISystem VN Translation Index">VN Translation Index</a><br /> -->
    <a href="<?= $this->baseUrl ?>/forum" title="CISVisual Forums">Forums</a><br />
    <a href="<?= $this->baseUrl ?>/faq" title="Frequently Asked Questions">Site FAQ</a><br />
    <a href="<?= $this->baseUrl ?>/about" title="About CISVisual">About CISV</a></p>
</div>
