<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Walkthrough Submitted</h1>
	<p>Thank you for your submission! Your walkthrough has been has been entered into the database.</p>
	<p>&nbsp;</p>
	<p><a href="<?= $this->baseUrl . '/title/' . $this->titleID ?>">&lt;&lt; Return to Title</a></p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
