<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
  <h1>Visual Novel Index</h1>
  <p class="strong">Listing titles <?= $this->start ?> - <?= $this->end ?> out of <?= $this->total ?>...</p>
  <p>&nbsp;</p>
  <p>Page:&nbsp;
<? for ($n = 1; $n <= $this->lastPage; $n++): ?>
<? if ($n != $this->page): ?>
  <a href="<?= $this->pageUrl . '/page/' . $n ?><? if (isset($this->desc)) echo '/desc' ?>" >
  <? if ($n != $this->lastPage): ?>
    <?= $n * $this->limit - ($this->limit - 1) . '-' . $n * $this->limit ?></a>&nbsp;
  <? else: ?>
    <?= $n * $this->limit - ($this->limit - 1) . '-' . $this->total ?></a>&nbsp;
  <? endif ?>
<? else: ?>
  <? if ($n != $this->lastPage): ?>
    <strong><?= $n * $this->limit - ($this->limit - 1) . '-' . $n * $this->limit ?></strong>&nbsp;
  <? else: ?>
    <strong><?= $n * $this->limit - ($this->limit - 1) . '-' . $this->total ?></strong>&nbsp;
  <? endif ?>
<? endif ?>
<? endfor ?>
  </p>
    <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <th width="60%"><a class="listcat" href="<?= $this->nameUrl ?>" >Visual Novel Name</a></th>
        <th width="15%"><a class="listcat" href="<?= $this->yearUrl ?>" >Release Year</a></th>
        <th width="25%"><a class="listcat" href="<?= $this->availableUrl ?>" >Availability in English</a>&nbsp;<a href="<?= $this->baseUrl . '/faq#translation'?>">?</a></th>
      </tr>
<? $count = 1; ?>
<? foreach ($this->data as $title): ?>
      <tr class="<?= (0 == $count % 2) ? 'tr1' : 'tr2'; $count++ ?>">
        <td width="60%"><a href="<?= $this->baseUrl . '/title/' . $title['titleID'] ?>"><?= $this->escape($title['titleName']) ?></a></td>
        <td width="15%"><?= $title['titleYear'] ?></td>
        <td width="25%"><?= $title['titleAvailable'] ?></td>
      </tr>
<? endforeach; ?>
    </table>
  <p>&nbsp;</p>
  <p><span style="font-size: 16px">Can't find a title?</span></p>
  <p><a style="font-size: 18px" href="<?= $this->baseUrl . '/title/add' ?>" title="Add a Title">Add it Now &gt;&gt;</a></p>
  <p>&nbsp;</p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
