<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Administration Console </h1>
	<p>&nbsp;</p>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="50%"><p class="category">Title Additions</p>
        <p><b><?= $this->escape($this->stats['pending']) ?></b> Submissions waiting to be approved.<br />
        <a href="<?= $this->baseUrl . '/admin/pending/' ?>">Title Approval List &gt;&gt;</a></p></td>
        <td width="50%"><p class="category">Title Edits</p>
        <p><b><?= $this->escape($this->stats['edits']) ?></b> Edits in <b><?= $this->escape($this->stats['transactions']) ?></b> transactions waiting for approval.<br />
        Edit Approval List &gt;&gt;</p></td>
      </tr>
      <tr>
        <td width="50%"><p class="category">User Permissions</p>
        <p><b><?= $this->escape($this->stats['users']) ?></b> Registered users.<br />
        User Permissions List &gt;&gt;</p></td>
        <td width="50%"><p class="category">Log Reports</p>
        <p><b>?</b> Log entries.<br />
        Log Viewer &gt;&gt;</p></td>
      </tr>
    </table>
	<p>&nbsp;</p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
