<?= $this->render('header.phtml') ?>
<?= $this->render('top.phtml') ?>

<div id="Content">
	<h1>Error!</h1>
	<p>CISVisual encountered an error while trying to process your visual novel entry review. The details of this error have been logged. Please contact the admin about this error so that it can be resolved.</p>
	<p><strong>Returned Message:</strong> <?= $this->message ?>
	<p>&nbsp;</p>
	<p><a href="<?= $this->baseUrl ?>/forum/index.php?board=13.0" title="Bug Report Forum">CISVisual Bug Report Forum >></a></p>
</div>

<?= $this->render('menu.phtml') ?>
<?= $this->render('footer.phtml') ?>
